- name: PHP7 | INSTALL PHP7 
  shell: [ ! -d /root/download ] && { mkdir /root/download }
  copy: src=/root/download/libmcrypt* dest=/root/download/
  shell: rpm -ivh /root/download/libmcrypt*
  yum:
    name:
      - wget
      - vim
      - pcre
      - pcre-devel
      - openssl
      - openssl-devel
      - gcc
      - gcc-c++
      - autoconf
      - libjpeg
      - libjpeg-devel
      - libpng
      - libpng-devel
      - freetype
      - freetype-devel
      - libxml2
      - libxml2-devel
      - zlib
      - zlib-devel
      - glibc
      - glibc-devel
      - glib2
      - glib2-devel
      - ncurses
      - ncurses-devel
      - curl
      - curl-devel
      - krb5-devel
      - libidn
      - libidn-devel
      - openldap
      - openldap-devel
      - nss_ldap
      - jemalloc-devel
      - cmake
      - boost-devel
      - bison
      - automake
      - libevent
      - libevent-devel
      - gd
      - gd-devel
      - libtool*
      - mcrypt
      - mhash
      - libxslt
      - libxslt-devel
      - readline
      - readline-devel
      - gmp
      - gmp-devel
      - libcurl
      - libcurl-devel
      - openjpeg-devel
    state: present
      
- name: EPEL-RELEASE | install rpm repo
  yum:
    name: epel-release
    state: latest
- name: REMIREPO | remi-release-7
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: latest
- name: PHP7 MODULES
  yum:
    name:
      - php74w 
      - php74w-cli 
      - php74w-common 
      - php74w-devel 
      - php74w-embedded 
      - php74w-fpm 
      - php74w-gd 
      - php74w-mbstring 
      - php74w-mysqlnd 
      - php74w-opcache 
      - php74w-pdo 
      - php74w-xml 
      - php74w-bcmath 
    state: present 
- name: PHP7 START
  service:
    name: php-fpm
    state: started